name: rampcheck
description: Aircraft maintenance app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  crypto: ^3.0.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  file_selector: ^1.0.3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:
  sqflite_common_ffi:

flutter:
  uses-material-design: true